Extended readme
JuliaSmoothOptimizers/.github pull request #1
Opened 2022-08-12 03:58 UTC by tmigot

Here is a first draft!

I was hoping to find a visual with statistics for the repo, but that doesn't seem easy to find.

My aim was to:
- introduce us
- give pointers to interested contributors
- give pointers for users

Seeing the list of solvers in this context confirms the interest for `JSOSuite`

2022-08-12 07:14 UTC, abelsiqueira requested changes
Hi Tangi, I've made a few comments that change a lot. As a rule of thumb, I think we should redirect to the website for longer content. Otherwise, we will have duplicated information and it's harder to keep track.
@dpo, what do you think?

2022-08-12 07:14 UTC, abelsiqueira commented on profile/README.md
> +JSO contains a collection of packages to model, solve, benchmark and analyze results efficiently.
```suggestion
JSO is an organization dedicated to numerical linear algebra and optimization, containing packages to model, solve, benchmark and analyze results efficiently.
We aim, among other things, to provide cutting-edge and original solvers and tools for researchers.
```
I would remove it because I don't think "we" should refer to people, i.e., the "we" = organization > us.
Also, I am not a researcher in these fields anymore, and also because it defines our interests.

The list of aims should be discussed, but I prefer to have something now and update it later.

2022-08-12 07:14 UTC, abelsiqueira commented on profile/README.md
> +### Linear algebra
I think we should talk only about the core packages here, and move the extra information to the website. Otherwise, the first contact is too overwhelming.

Instead of focusing on the package, we could focus on the target audience:
- "I want to solve a linear system" -> Go here
- "I want to solve an optimization problem" -> Go here
- "I want to build an optimization method" -> Go here

2022-08-19 14:54 UTC, tmigot commented on profile/README.md
> +### Linear algebra
That's probably better, I think we are missing a couple of things there maybe. I would say
- "I want to solve a linear system" -> Krylov.jl (but it doesn't highlight the factorizations)
- "I want to solve an optimization problem" -> JSOSuite.jl
- "I want to build an optimization method" -> SolverCore.jl (after https://github.com/JuliaSmoothOptimizers/SolverCore.jl/issues/32 )

2022-08-20 01:17 UTC, dpo commented on profile/README.md
> +### Linear algebra
I agree that it's better to focus on the what the user is trying to do.

For now, we should just list the relevant packages in each category. In time, I would like to have "meta packages" that bring together related packages (Krylov/MUMPS/HSL/LDL/QRMumps, JSOSolver/NLPModelsIpopt/NLPModelsKnitro/NCL/DCI/etc, SolverBenchmark/BenchmarkProfile/etc, ...). We'll update this README as we go.

2022-08-20 01:17 UTC, dpo commented on profile/README.md
> +- Efficient modelisation of linear systems 🤠: [LinearOperators.jl](https://github.com/JuliaSmoothOptimizers/LinearOperators.jl), [SparseMatricesCOO.jl](https://github.com/JuliaSmoothOptimizers/Sparse
`sed -e s/modelisation/modeling/g`

2022-08-20 01:17 UTC, dpo commented on profile/README.md
> +- Preconditionner: [BasicLU.jl](https://github.com/JuliaSmoothOptimizers/BasicLU.jl)
LimitedLDL would be here, not in factorizations.

2022-08-20 01:17 UTC, dpo commented on profile/README.md
> +- Test problems 🤼: [SuiteSparseMatrixCollection.jl](https://github.com/JuliaSmoothOptimizers/SuiteSparseMatrixCollection.jl)
Test systems.

2022-08-20 01:17 UTC, dpo commented on profile/README.md
> +- Test problems 🤺: [NLSProblems.jl](https://github.com/JuliaSmoothOptimizers/NLSProblems.jl), [OptimizationProblems.jl](https://github.com/JuliaSmoothOptimizers/OptimizationProblems.jl)
and BundleAdjustment

2022-08-20 01:17 UTC, dpo commented on profile/README.md
> +- Model general optimization problems 💪: [ADNLPModels.jl](https://github.com/JuliaSmoothOptimizers/ADNLPModels.jl), [NLPModelsJuMP](https://github.com/JuliaSmoothOptimizers/NLPModelsJuMP.jl), [AmplNL
I would put JuMP, AMPL and CUTEst in a category "load models from other modeling systems"

2022-08-20 01:17 UTC, dpo commented on profile/README.md
> +- Minimum degree ordering 🦅: [AMD.jl](https://github.com/JuliaSmoothOptimizers/AMD.jl)
AMD would go with the factorizations.

2022-08-20 01:17 UTC, dpo commented on profile/README.md
> +- Model PDE-constrained optimization problems 🧘: [PDENLPModels.jl](https://github.com/JuliaSmoothOptimizers/PDENLPModels.jl)
These two would go into the modeling section.

2022-08-22 12:40 UTC, tmigot commented on profile/README.md
> +### Linear algebra
Thanks for the feedback. I made an issue for this https://github.com/JuliaSmoothOptimizers/.github/issues/2 and added @dpo suggestions.

2022-08-26 19:52 UTC, abelsiqueira approved these changes
Thanks, Tangi.

2022-08-29 15:28 UTC, merged